// <auto-generated />
using CaptoneProject.Services.ProfileAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaptoneProject.Services.ProfileAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250417065332_initialmigrations")]
    partial class initialmigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaptoneProject.Services.ProfileAPI.Models.Profile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("CoursesNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfCourcesEnrolled")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rank")
                        .HasColumnType("int");

                    b.Property<int>("rollNumber")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Profile");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            CoursesNames = "[\"python\",\"C\\u002B\\u002B\"]",
                            NumberOfCourcesEnrolled = 2,
                            PhoneNumber = "1234567",
                            email = "Ajith@123",
                            rank = 1,
                            rollNumber = 6655,
                            userName = "Ajith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
